// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function multiplay(x, y) {
  return Caml_int32.imul(x, y) / 2 | 0;
}

function add(x, y, z) {
  return (x + y | 0) + z | 0;
}

var ruleList = /* :: */[
  /* tuple */[
    "",
    /* true */1
  ],
  /* :: */[
    /* tuple */[
      "",
      /* false */0
    ],
    /* [] */0
  ]
];

var result = 118;

exports.ruleList  = ruleList;
exports.multiplay = multiplay;
exports.add       = add;
exports.result    = result;
/* No side effect */
